sequenceDiagram
  autonumber
  participant LRC as LoRaWAN App
  participant GW as Gateway
  participant TPM as AirVibe

  Note over LRC,TPM: Get a Machine Saver TPM/VSM Factory Upgrade.bin File (customers cannot create)

  LRC->>GW: Command Downlink - [Initialize Upgrade]<br> Port: 22 <br> 0x0500 + upgrade.bin_bytesize (4 Bytes LittleEndian)
  GW->>TPM: Command Downlink - [Initialize Upgrade]<br> Port: 22 <br> 0x0500 + upgrade.bin_bytesize (4 Bytes LittleEndian)
  TPM->>TPM: Enter Class C Mode
  TPM-->>GW: Initialize Upgrade Acknowledgment Uplink <br> Type 16 (0x10) <br> (1 Byte, Error Code=0)
  GW->>GW: Enter Class C Mode
  GW-->>LRC: Initialize Upgrade Acknowledgment Uplink <br> Type 16 (0x10) <br> (1 Byte, Error Code=0)

  Note over LRC,TPM: App sends upgrade.bin chunked into data blocks n=0..N-1 (51 Bytes, 16-bit Blocks, LittleEndian)
  loop Data blocks
    LRC->>GW: Upgrade Data Downlink <br> Port: 25 <br> block_num (2 Bytes LittleEndian) + upgrade.bin_chunk (51 Bytes)
    GW->>TPM: Upgrade Data Downlink <br> Port: 25 <br> block_num (2 Bytes LittleEndian) + upgrade.bin_chunk (51 Bytes)
  end
  Note over LRC,TPM: If upgrade.bin size/51 has a remainder, then the last block will be shorter.

  LRC->>GW: Command Downlink - [Verify Upgrade]<br> Port: 22 <br> 0x0600
  GW->>TPM: Command Downlink - [Verify Upgrade]<br> Port: 22 <br> 0x0600
  TPM->>GW: Upgrade Verification Status Uplink <br> Type 17 (0x11) <br>(flag=1, count<=25, list)
  GW->>LRC: Upgrade Verification Status Uplink <br> Type 17 (0x11) <br>(flag=1, count<=25, list)
  LRC->>LRC: Check Missing Data Blocks

  alt Upgrade Verification Status Uplink has Missing Data Blocks
    loop Resend Missing & Verify Until No Missing Blocks Remain
      LRC->>GW: Upgrade Data Downlink (Port 25) - resend blocks {b1..bN}
      GW->>TPM: Upgrade Data Downlink (Port 25) - resend blocks {b1..bN}
      LRC->>GW: Command Downlink - [Verify Upgrade]<br> Port: 22 <br> 0x0600
      GW->>TPM: Command Downlink - [Verify Upgrade]<br> Port: 22 <br> 0x0600
      TPM-->>GW: Upgrade Verification Status Uplink <br> Type 17 (0x11) <br>(flag=0, count=0)
      GW-->>LRC: Upgrade Verification Status Uplink <br> Type 17 (0x11) <br>(flag=0, count=0)
    end
  else No blocks missed
    TPM->>TPM: CRC16 validate image
    TPM->>TPM: Selects Upgrade Target <br> VSM or TPM <br> (based on internal hardware code)
    TPM->>TPM: Apply Upgrade
    TPM->>TPM: Reverts Back to Class A
  end

  TPM-->>LRC: Upgrade Verification Status Uplink
  LRC-->>GW: Upgrade Verification Status Uplink
  GW->>GW: Switch to Class A
